dist: trusty
language: python
python:
  - "2.7"

sudo: required

cache:
    directories:
        - $HOME/qemu
        - $HOME/images

before_script:
    - python2 --version
    - python3 --version
    - python --version
    - QEMU_ARCHES="arm" bash -e ci/travis-qemu.sh
    - export PATH=$PATH:$HOME/qemu/bin
    - mkdir -p $HOME/images
    - wget "http://lede-project.tetaneutral.net/releases/17.01.0/targets/armvirt/generic/lede-17.01.0-r3205-59508e3-armvirt-zImage-initramfs" -o $HOME/images/lede.kernel

script:
  - ssh-keygen -f $HOME/.ssh/id_rsa -t rsa -P ''
  - sudo cp $HOME/.ssh/id_rsa $HOME/.ssh/authorized_keys
  - sudo chmod 700 $HOME/.ssh
  - sudo chmod 600 $HOME/.ssh/authorized_keys
  - python3 --version
  - ln -sf $HOME/images/lede.kernel .
  - ./test.py --ssh-user $USER
  - ./test_lede.sh $USER
