language: python
python:
  - "3.6"

sudo: false

cache:
    directories:
        - $HOME/qemu
        - $HOME/images

before_script:
    - QEMU_ARCHES="arm" bash -e ci/travis-qemu.sh
    - export PATH=$PATH:$HOME/qemu/bin
    - mkdir -p $HOME/images
    - wget "http://lede-project.tetaneutral.net/releases/17.01.0/targets/armvirt/generic/lede-17.01.0-r3205-59508e3-armvirt-zImage-initramfs" -o $HOME/images/lede.kernel

script:
  - ln -sf $HOME/images/lede.kernel .
  - ./test.py
  - ./test_lede.sh
